apiVersion: v1
kind: Secret
metadata:
  name: connection-secret
type: Opaque
stringData:
  connectionString: ${DATABASE_CONNECTIONSTRING}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: order-service-migrations
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: order-service-migrations
          image: mystfan/order-service-migrations:${VERSION}
          env:
            - name: DATABASE__CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: connection-secret
                  key: connectionString