apiVersion: v1
kind: Secret
metadata:
  name: connection-secret
type: Opaque
stringData:
  connectionString: ${DATABASE_CONNECTIONSTRING}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: orders
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: order-service
          image: mystfan/order-service:${VERSION}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DATABASE__CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: connection-secret
                  key: connectionString
            - name: RABBITMQ__USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ__HOST
              value: 'rabbitmq'  
